### ISSUE TITLE
Create a model for a User/Trainer object

### ISSUE THREAD

**Issue by Monbrey** [Monbrey/urpg-discord#1]
Dicebot legacy code has a few different representations of a user; for FFA pinging and beta ELO tracking.
Should look at these and flesh out into a proper User/Trainer object class and store in mLab.

Considerations:
- Should a generic user object be generated with every join, or only on starter requests?
- Should two separate objects be stored - one for a generic Discord presence and one for the game logic?
- Make a list of Trainer fields (cash, join date, battle record etc)

**Comment by vanessasickles** [comment]
@Monbrey 
- Probably only on starter requests; people leave and join the server all of the time, and those who join the server might not necessarily carry through with joining the game. We could also use a true/false of if they've chosen the starter or not to keep the bot's Welcome message from spamming people who are already well into the game. This also keeps it from storing unnecessary profiles/people.
- This one's up to you - what other features would require a generic Discord presence as opposed to a Trainer-based one? If not, it might be easier to just keep them one in the same.
- Good, Anakin, gooooooood.
